### ISSUE TITLE
next gen Trill sensors have QWIIC connectors, color code of wires chaged

### ISSUE THREAD

**Issue by mxa** [BelaPlatform/fritzing#1]
The color code of the cables for the QWIIC connector is different, should there be an update?

**Comment by giuliomoro** [comment]
Yes , though I have not seen the grove cables we are shipping. 

Btw maybe what we need in the datasheet is a 
Diagram and pinout of the grove connector and leave the colors out of the _picture_

**Comment by mxa** [comment]
? New Datasheet/TRILL has QWIIC, not GROVE

**Comment by giuliomoro** [comment]
I meant Qwiic. I mean, a Fritzing wiring diagram  is not found often in a datasheet

**Comment by mxa** [comment]
OK, this issue is about the fritzing library though. Should it be updated to reflect the colours of the QWIIC cable?

**Comment by roberthjack** [comment]
Yes, good idea to update the fritzing library. And perhaps to have both
revisions for posterity's sake.

**Comment by mxa** [comment]
fixed with b9423760d8ab8b1fda517edd62bb46daeb382ae4
